from flask import make_response, abort

name: double resource
description: define baremetal and virtual machine resources to be provisioned

baremetal:
  name: baremetal-node
  role: node
  provider:
    name: baremetal
    credential: baremetal-creds
    image: rhel-7.5-server-x86_64-released
    flavor: m1.small
    networks:
      - '{{ network }}'
    floating_ip_pool: "10.8.240.0"
    keypair: '{{ keypair }}'
  ansible_params:
    ansible_user: cloud-user
    ansible_ssh_private_key_file: "keys/{{ keypair }}"

virtual-machine:
  name: virtual-machine-node
  role: node
  provider:
    name: virtual-machine
    credential: virtual-machine-creds
    image: rhel-7.5-server-x86_64-released
    flavor: m1.small
    networks:
      - '{{ network }}'
    floating_ip_pool: "10.8.240.1"
    keypair: '{{ keypair }}'
  ansible_params:
    ansible_user: cloud-user
    ansible_ssh_private_key_file: "keys/{{ keypair }}"
  