swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1"
  title: Swagger ReST Article
consumes:
  - application/yml
produces:
  - application/yml

basePath: /api

# Paths supported by the server application
paths:
  /requirements:
    get:
      operationId: requirements.read_all
      tags:
        - Requirements
      summary: Read the entire list of requirements
      description: Read the list of requirements
      parameters:
        - name: length
          in: query
          type: integer
          description: Number of requirements to get from Requirements
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start gathering requirements
          required: false
      responses:
        200:
          description: Successfully read requirements list operation
          schema:
            type: array #provision
            items:
              properties:
                0:
                  type: array
                  items:
                    properties:
                      name:
                        type: string
                      role:
                        type: string
                      provider:
                        type: array
                        items:
                          properties:
                            name:
                              type: string
                            credential:
                              type: string
                            image:
                              type: string
                            flavor:
                              type: string
                            networks:
                              type: string
                            floating_ip_pool:
                              type: string
                            keypair:
                              type: string
                      ansible_params:
                        type: array
                        items:
                          properties:
                            ansible_user:
                              type: string
                            ansible_ssh_private_key_file:
                              type: string
                1:
                  type: array
                  items:
                    properties:
                      name:
                        type: string
                      role:
                        type: string
                      provider:
                        type: array
                        items:
                          properties:
                            name:
                              type: string
                            credential:
                              type: string
                            image:
                              type: string
                            flavor:
                              type: string
                            networks:
                              type: string
                            floating_ip_pool:
                              type: string
                            keypair:
                              type: string
                      ansible_params:
                        type: array
                        items:
                          properties:
                            ansible_user:
                              type: string
                            ansible_ssh_private_key_file:
                              type: string

  /requirements/{container}:
    get:
      operationId: requirements.read_one
      tags:
        - Requirements
      summary: Read one set of requirements (container) from the requirements list
      description: Read one set of requirements (container) from the requirements list
      parameters:
        - name: container
          in: path
          description: Last name of the element to get from the list
          type: string
          required: True
      responses:
        200:
          description: Successfully read element from requirements list operation
          schema:
            type: array
            items:
              properties:
                name:
                  type: string
                role:
                  type: string
                provider:
                  type: array
                  items:
                    properties:
                      name:
                        type: string
                      credential:
                        type: string
                      image:
                        type: string
                      flavor:
                        type: string
                      networks:
                        type: string
                      floating_ip_pool:
                        type: string
                      keypair:
                        type: string
                ansible_params:
                  type: array
                  items:
                    properties:
                      ansible_user:
                        type: string
                      ansible_ssh_private_key_file:
                        type: string