swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

# basePath: /api

# Paths supported by the server application
paths:
  /requirements/{container}:
    get:
      operationId: requirements.read_one
      tags:
        - Requirements
      summary: Read one set of requirements (container) from the requirements list
      description: Read one set of requirements (container) from the requirements list
      parameters:
        - name: container
          in: path
          description: Last name of the element to get from the list
          type: string
          required: True
      responses:
        200:
          description: Successfully read element from requirements list operation
          schema:
            type: array
            items:
              properties:
                name:
                  type: string
                role:
                  type: string
                provider:
                  type: array
                  items:
                    properties:
                      name:
                        type: string
                      credential:
                        type: string
                      image:
                        type: string
                      networks:
                        type: string
    post:
      operationId: requirements.send_one
      tags:
        - Requirements
      summary: Post a single set of requirements
      description: Post a single set of requirements
      parameters:
        - name: container
          in: path
          description: Last name of the element to get from the list
          type: string
          required: True
      responses:
        201:
          description: Successfully posted requirement
          schema:
            type: array
            items:
              properties:
                name:
                  type: string
                role:
                  type: string
                provider:
                  type: array
                  items:
                    properties:
                      name:
                        type: string
                      credential:
                        type: string
                      image:
                        type: string
                      networks:
                        type: string
  /requirements:
    post:
      operationId: requirements.send_all
      tags:
        - Requirements
      summary: Post the entire requirements list
      description: Post the entire requirements list
      parameters:
        - name: reqList
          in: body
          description: Entire requirements list
          required: True
          schema:
            type: array
            items:
              properties:
                name:
                  type: string
                role:
                  type: string
                provider:
                  type: array
                  items:
                    properties:
                      name:
                        type: string
                      credential:
                        type: string
                      image:
                        type: string
                      networks:
                        type: string
      responses:
        201:
          description: Successfully posted requirements
  
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /tkrose25/gateway/1
schemes:
 - https