swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /requirements:
    post:
      operationId: app.gateway.gw_post
      tags:
        - Requirements
      summary: Post the entire requirements list
      description: Post the entire requirements list
      parameters:
        - name: reqList
          in: body
          description: Entire requirements list
          required: True
          schema:
            type: object
      responses:
        201:
          description: Successfully posted requirements
    get:
      operationId: gateway.gw_get
      tags:
        - Requirements
      summary: Post the entire requirements list
      description: Post the entire requirements list
      responses:
        201:
          description: Successfully posted requirements
  /baremetal:
    post:
      operationId: app.baremetal.bm_post
      tags:
        - Requirements
      summary: Receive BM provisioning section
      description: Receive BM provisioning section
      parameters:
        - name: bmReq
          in: body
          description: BM provisioning requirement section
          required: True
          schema:
            type: object
      responses:
        201:
          description: Successfully posted requirements
  /virtualmachine:
    post:
      operationId: app.virtualmachine.vm_post
      tags:
        - Requirements
      summary: Receive the VM provisioning section
      description: Receive the VM provisioning section
      parameters:
        - name: vmReq
          in: body
          description: VM provisioning requirement section
          required: True
          schema:
            type: object
      responses:
        201:
          description: Successfully posted requirements