swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /requirements:
    get:
      operationId: requirements.read_all
      tags:
        - Requirements
      summary: Read the entire list of requirements
      description: Read the list of requirements
      parameters:
        - name: length
          in: query
          type: integer
          description: Number of requirements to get from Requirements
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start gathering requirements
          required: false
      responses:
        200:
          description: Successfully read requirements list operation
          schema:
            type: array
            items:
              properties:
                fname:
                  type: string
                lname:
                  type: string
                timestamp:
                  type: string

    post:
      operationId: requirements.create
      tags:
        - Requirements
      summary: Create an element and add it to the requirements list
      description: Create a new element in the requirements list
      parameters:
        - name: element
          in: body
          description: Element to create
          required: True
          schema:
            type: object
            properties:
              fname:
                type: string
                description: First name of element to create
              lname:
                type: string
                description: Last name of element to create
      responses:
        201:
          description: Successfully created element in list

  /requirements/{lname}:
    get:
      operationId: requirements.read_one
      tags:
        - Requirements
      summary: Read one element from the requirements list
      description: Read one element from the requirements list
      parameters:
        - name: lname
          in: path
          description: Last name of the element to get from the list
          type: string
          required: True
      responses:
        200:
          description: Successfully read element from requirements list operation
          schema:
            properties:
              fname:
                type: string
              lname:
                type: string
              timestamp:
                type: string
